### ISSUE TITLE
Sprite Builder AndroidAlertDialogBuilder Error 

### ISSUE THREAD

**Issue by wieseljonas** [spritebuilder/SpriteBuilder#1169]
I cannot manage to use the Android Alert through the bridge API.

Here is my code:

```
    dispatch_async(dispatch_get_main_queue(), ^{
         AndroidAlertDialogBuilder *builder = [[AndroidAlertDialogBuilder alloc] initWithContext:self theme:AndroidAlertDialogThemeHoloDark];

         [builder setTitleByCharSequence:@"You have to place every boat!"];
         [builder setMessageByCharSequence:message];

        [builder setPositiveButton:@"Yes" onClickListener:nil];

        [builder setNegativeButton:@"No" onClickListener:nil];

        [builder show];

});
```

I get I null pointer exception any ideas why?

```
 W/System.err( 5746): java.lang.NullPointerException
 W/System.err( 5746):   at android.widget.Toast.<init>(Toast.java:93)
 W/System.err( 5746):   at android.widget.Toast.makeText(Toast.java:241)
 W/System.err( 5746):   at com.apportable.RunLoop.idle(Native Method)
 W/System.err( 5746):   at com.apportable.RunLoop$1.queueIdle(RunLoop.java:15)
 W/System.err( 5746):   at android.os.MessageQueue.next(MessageQueue.java:207)
 W/System.err( 5746):   at android.os.Looper.loop(Looper.java:123)
 W/System.err( 5746):   at android.app.ActivityThread.main(ActivityThread.java:5086)
 W/System.err( 5746):   at java.lang.reflect.Method.invokeNative(Native Method)
 W/System.err( 5746):   at java.lang.reflect.Method.invoke(Method.java:515)
 W/System.err( 5746):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
 W/System.err( 5746):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
 W/System.err( 5746):   at dalvik.system.NativeStart.main(Native Method)
 D/NavalBattleiOS( 5746): 2014-11-11 02:41:33.852 NavalBattleiOS[5746:2795] Unhandled exception (null description)
 E/NavalBattleiOS( 5746): 4-11-11 02:41:32.520 org.cocos2d.NavalBattleiOS[5746:59381d98] CGFONTS!!!!: SFNTTABLE: id: 1 lang: 0x0409 platform 3 name: Roboto
 E/NavalBattleiOS( 5746): 2014-11-11 02:41:32.520 org.cocos2d.NavalBattleiOS[5746:59381d98] CGFONTS!!!!: SFNTTABLE: id: 2 lang: 0x0409 platform 3 name: Regular
 E/NavalBattleiOS( 5746): 2014-11-11 02:41:32.521 org.cocos2d.NavalBattleiOS[5746:59381d98] CGFONTS!!!!: SFNTTABLE: id: 3 lang: 0x0409 platform 3 name: Google:Roboto:2013
 E/NavalBattleiOS( 5746): 2014-11-11 02:41:32.522 org.cocos2d.NavalBattleiOS[5746:59381d98] CGFONTS!!!!: SFNTTABLE: id: 4 lang: 0x0409 platform 3 name: Roboto Regular
 E/NavalBattleiOS( 5746): 2014-11-11 02:41:32.522 org.cocos2d.NavalBattleiOS[5746:59381d98] WARNING: use of non Postscript name 'Roboto Regular', assume it is full font name...
 E/NavalBattleiOS( 5746): 
 E/NavalBattleiOS( 5746): terminating with uncaught exception of type JavaRuntimeException
```

**Comment by wieseljonas** [comment]
Solution found!!! took a while please update the website!

you have to declare initWithContext wth CCActivity!

```
    AndroidAlertDialogBuilder *builder = [[AndroidAlertDialogBuilder alloc] initWithContext:[ CCActivity currentActivity ]];
```

**Comment by wieseljonas** [comment]
However no idea how to set those onClickListeners to fire a method!

**Comment by khanbhai89** [comment]
As per @wieseljonas comment this issue is ready to be closed.
