### ISSUE TITLE
CCTextField error when compiling to Android

### ISSUE THREAD

**Issue by wieseljonas** [spritebuilder/SpriteBuilder#1222]
I have a node with a CCTextField when I add it to a scene it give me this error on android. Works fine on iOS

```
W/System.err(19418): java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
W/System.err(19418):    at android.view.ViewGroup.addViewInner(ViewGroup.java:3564)
W/System.err(19418):    at android.view.ViewGroup.addView(ViewGroup.java:3417)
W/System.err(19418):    at android.view.ViewGroup.addView(ViewGroup.java:3362)
W/System.err(19418):    at android.view.ViewGroup.addView(ViewGroup.java:3338)
W/System.err(19418):    at com.apportable.RunLoop.idle(Native Method)
W/System.err(19418):    at com.apportable.RunLoop$1.queueIdle(RunLoop.java:15)
W/System.err(19418):    at android.os.MessageQueue.next(MessageQueue.java:207)
W/System.err(19418):    at android.os.Looper.loop(Looper.java:123)
W/System.err(19418):    at android.app.ActivityThread.main(ActivityThread.java:5086)
W/System.err(19418):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(19418):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(19418):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/System.err(19418):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/System.err(19418):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rkachowski** [comment]
I can't reproduce this on the latest version, If you manage to reproduce it can you create a new issue and attach a test case? Thanks
