### ISSUE TITLE
APK is not starting: Spritebuilder 1.4.7 + Lastest Android Plugin from Store and Android 5.0.1

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#1345]
Hi, I made a complete new empty project in SpriteBuilder 1.4.7 (downloaded today). Still cannot execute any APK on my Android device running 5.0.1.

`I/v       (11538): file_io.c:1779 __wrap_open: Could not open real file path /data/data/org.cocos2d.ohRUN/files/Library/Preferences/org.cocos2d.ohRUN.plist with error No such file or directory
Loaded library libJavaFoundation.so
Loaded library libGraphicsServices.so
Loaded library libCoreGraphics.so
Loaded library libpango.so
Loaded library libJavaKit.so
Loaded library libAndroidKit.so
E/art     (11538): Failed to register non-native method com.apportable.androidkit.block.AndroidBlockSensorEventListener.onAccuracyChanged(Landroid/hardware/Sensor;I)V as native
F/art     (11538): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI NewStringUTF called with pending exception 'java.lang.NoSuchMethodError' thrown in java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String):-2
F/art     (11538): art/runtime/check_jni.cc:65]     in call to NewStringUTF
F/art     (11538): art/runtime/check_jni.cc:65]     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)
F/art     (11538): art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable
F/art     (11538): art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x73d342e0 self=0xb7a354f8
F/art     (11538): art/runtime/check_jni.cc:65]   | sysTid=11538 nice=0 cgrp=apps sched=0/0 handle=0xb6fbdec8
F/art     (11538): art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=49 stm=21 core=0 HZ=100
F/art     (11538): art/runtime/check_jni.cc:65]   | stack=0xbe79b000-0xbe79d000 stackSize=8MB
F/art     (11538): art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #00 pc 00004c58  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #01 pc 000034c1  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #02 pc 00252985  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+84)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #03 pc 00236463  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+162)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #04 pc 000b12a5  /system/lib/libart.so (art::JniAbort(char const*, char const*)+620)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #05 pc 000b19d5  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #06 pc 000b4c5d  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv*, int, char const*)+1324)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #07 pc 000bda65  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+28)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #08 pc 0000a944  /data/app/org.cocos2d.ohRUN-1/lib/arm/libbridge_runtime.so (_JNIEnv::NewStringUTF(char const*)+48)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #09 pc 0000a6b0  /data/app/org.cocos2d.ohRUN-1/lib/arm/libbridge_runtime.so (jni_findClass+44)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #10 pc 0001ded8  /data/app/org.cocos2d.ohRUN-1/lib/arm/libbridge_runtime.so (resolve_javaClass(bridge_class_s*)+36)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #11 pc 0001de0c  /data/app/org.cocos2d.ohRUN-1/lib/arm/libbridge_runtime.so (bridge_resolveJavaClass+244)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #12 pc 0000f308  /data/app/org.cocos2d.ohRUN-1/lib/arm/libbridge_runtime.so (bridge_initializeClass(bridge_class_s*)+1340)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #13 pc 0000ed74  /data/app/org.cocos2d.ohRUN-1/lib/arm/libbridge_runtime.so (bridge_initialize_classes+360)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #14 pc 0000f858  /data/app/org.cocos2d.ohRUN-1/lib/arm/libbridge_runtime.so (__load_bridge+68)
F/art     (11538): art/runtime/check_jni.cc:65]   native: #15 pc 0002a000  /data/app/org.cocos2d.ohRUN-1/lib/arm/libAndroidKit.so (__vrt_load+836)
F/art     (11538): art/runtime/check_jni.cc:65]   at java.lang.Runtime.nativeLoad(Native method)
F/art     (11538): art/runtime/check_jni.cc:65]   at java.lang.Runtime.doLoad(Runtime.java:428)
F/art     (11538): art/runtime/check_jni.cc:65]   - locked <0x31a48401> (a java.lang.Runtime)
F/art     (11538): art/runtime/check_jni.cc:65]   at java.lang.System.load(System.java:982)
F/art     (11538): art/runtime/check_jni.cc:65]   at com.apportable.Library.load(Library.java:148)
F/art     (11538): art/runtime/check_jni.cc:65]   at com.apportable.LibraryLoader.load(LibraryLoader.java:78)
F/art     (11538): art/runtime/check_jni.cc:65]   at com.apportable.RuntimeService.loadLibraries(RuntimeService.java:388)
F/art     (11538): art/runtime/check_jni.cc:65]   at com.apportable.ApportableGLActivity.onCreate(ApportableGLActivity.java:17)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.app.Activity.performCreate(Activity.java:5933)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.app.ActivityThread.access$800(ActivityThread.java:144)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:102)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:135)
F/art     (11538): art/runtime/check_jni.cc:65]   at android.app.ActivityThread.main(ActivityThread.java:5221)
F/art     (11538): art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke!(Native method)
F/art     (11538): art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke(Method.java:372)
F/art     (11538): art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
F/art     (11538): art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
F/art     (11538): art/runtime/check_jni.cc:65] 
[New Thread 11544]`

**Comment by Shahidwerplay** [comment]
This issue is fixed.

SpriteBuilder-1.4.7 with build sbandroid-starter-9f673a75
Mac OS X: 10.10.
XCode: 6.2.
Device Nexus 6/5.0.1
