### ISSUE TITLE
Application crashes with EXC_BAD_ACCESS on Sub File node infinite recursion (due to self-reference)

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#761]
1. Launch Sprite Builder.
2. Create a new scene "1.ccb".
3. Create a new layer called "untitled.ccb".
4. Drag and Drop Sub node from nodes menu on the stage in untitled.ccb.
5. Select "Untitled.ccb" (i.e. ccb file itself) as the sub node from the property inspector.
6. Drag and Drop Sub node from nodes menu on the stage in 1.ccb.
7. Select "Untitled.ccb" as the sub node from the property inspector.
   
   -- Result: Application crashes when user selects untitled.ccb file as sub node.

Video: https://drive.google.com/file/d/0B5KeRaV3CWUaakdBZHdUNmxMMjA/edit?usp=sharing

Mac OS X: 10.9.2.
Build: SpriteBuilder-1.2.0-beta.2.zip

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilderPro/f28e9cfda22d61aa5b784b7e7d25f5bae0fe1323/SpriteBuilderPro-sb-1.2.0-beta.7-dcf-release_3.0.0-alpha.0-f28e9cfda22d61aa5b784b7e7d25f5bae0fe1323_c45808d300864d44.dmg

Mac OSX: 10.9.2.
XCode: 5.0.

**Comment by LearnCocos2D** [comment]
This is actually much simpler to reproduce (verified with this week's develop branch):
1. Create new SpriteBuilder project, open MainScene.ccb.
2. Drag MainScene.ccb onto the stage (on itself).
3. Publish and behold: EXC_BAD_ACCESS

At a minimum the CCBReader should spit out an error message that helps to resolve the issue.

This can only be fixed within SB by traversing the entire Sub File node tree and checking each referenced CCB file for possible recursion in one of its parents. I bet the reader has no easy way of determining the issue as well, but it can certainly create a hierarchy of already loaded CCB files while loading and checking (in debug builds) whether the ccb file to be loaded is one that's already loaded somewhat higher in the hierarchy.

**Hint:** a sure sign of this issue is if the call stack goes in the high thousands, in this case even above 10,000:

```
#10693  0x0013cb14 in -[CCBReader readPropertyForNode:parent:isExtraProp:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:905
#10694  0x00142562 in -[CCBReader readNodeGraphParent:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1428
#10695  0x001436e2 in -[CCBReader readNodeGraphParent:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1606
#10696  0x00144edb in -[CCBReader readFileWithCleanUp:actionManagers:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1764
#10697  0x0013cb14 in -[CCBReader readPropertyForNode:parent:isExtraProp:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:905
#10698  0x00142562 in -[CCBReader readNodeGraphParent:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1428
#10699  0x001436e2 in -[CCBReader readNodeGraphParent:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1606
#10700  0x00144edb in -[CCBReader readFileWithCleanUp:actionManagers:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1764
#10701  0x0013cb14 in -[CCBReader readPropertyForNode:parent:isExtraProp:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:905
#10702  0x00142562 in -[CCBReader readNodeGraphParent:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1428
#10703  0x001436e2 in -[CCBReader readNodeGraphParent:] at /depot-koboldkit/sbbookprojects/SpriteBuilder Documentation Projects/MyFirstProject.spritebuilder/Source/libs/cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1606
```

**Comment by sana20** [comment]
This issue is fixed.
Mac OS 10.10.1.
SB version 1.4.7
XCode 6.1
