### ISSUE TITLE
Removing and readding BridgeKitV3.framework breaks project (can't find framework at path)

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#998]
Just found this out the hard way.

In the "xxxx Java" target the BridgeKitV3.framework is linked. Xcode lists this framework in red color even though it's indeed working. While trying to find the cause of a linker problem, I removed the BridgeKitV3.framework and re-added the one that Xcode offered in the libraries list. Henceforth the framework was no longer shown in red, which is a good sign, right?

Unfortunately this will lead to linker errors:

```
Error: Cannot find framework at path /Users/gaminghorror/Library/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid0.9.sdk/System/Library/Frameworks/../../../../Users/gaminghorror/Library/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid0.9.sdk/System/Library/Frameworks/BridgeKitV3.framework
Traceback (most recent call last):
  File "/Users/gaminghorror/Library/Application Support/Developer/Shared/Xcode/Plug-ins/IDEJavaSupportCore.xcplugin/Contents/Resources/java-build-jar.py", line 177, in <module>
    main()
  File "/Users/gaminghorror/Library/Application Support/Developer/Shared/Xcode/Plug-ins/IDEJavaSupportCore.xcplugin/Contents/Resources/java-build-jar.py", line 64, in main
    assert os.path.exists(framework_path)
AssertionError
```

Notice the path points to the file, then backtracks (../../) and then the whole path is appended again. Of course that won't work:

```
/Users/gaminghorror/Library/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid0.9.sdk/System/Library/Frameworks/../../../../Users/gaminghorror/Library/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid0.9.sdk/System/Library/Frameworks/BridgeKitV3.framework
```

If you open the .xcodeproj's pbxproj file you'll find two BridgeKitV3.framework references (Xcode doesn't actually remove the one that was there when the project was created). To fix this issue, you have to edit the path of the newly added BridgeKit framework to read:
 `path = System/Library/Frameworks/BridgeKitV3.framework;`

The entire line reads like so:

```
        5B12100B19748281004C1E1D /* BridgeKitV3.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = BridgeKitV3.framework; path = System/Library/Frameworks/BridgeKitV3.framework; sourceTree = SDKROOT; };
```

Note: simply deleting the newly added framework from the pbxproj won't work since Xcode will lose its internal references and probably crash when trying to build. Once the BridgeKit framework has been removed and readded, one must edit the newly added bridgekit framework's path to fix the build issue.

**Comment by LearnCocos2D** [comment]
If you remove and readd the BridgeKitV3 framework from the "xxxx Android" target it doesn't seem to break things. Perhaps this is because the "xxxx Java" target already links to the framework and is a dependency for "xxxx Android".

**Comment by csmillie** [comment]
I can confirm the problem with java target.  It seems to effect any framework added to that target.  I tried adding CoreJava and it generates the following error:

Error: Cannot find framework at path /Library/SBAndroid/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid.sdk/System/Library/Frameworks/../../../../../../Library/SBAndroid/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid.sdk/System/Library/Frameworks/CoreJava.framework

Other targets are not effected.

**Comment by collinjackson** [comment]
There's a new release of the Android plugin coming out soon -- let's see if it works for you. Things are early and still changing a lot, so note that it doesn't currently upgrade existing SpriteBuilder projects to work with Android -- but it should at least work on projects created from scratch with the latest SpriteBuilder beta.

**Comment by NickyWeber** [comment]
Is this related? https://github.com/spritebuilder/SpriteBuilder/pull/1268/files?

**Comment by csmillie** [comment]
It looks like it's removing BridgeKit from the Java target but I don't think it addresses the issue with adding frameworks to the target and getting an incorrect path to them.  I haven't test these changes though...
